### ISSUE TITLE
Cannot delete users

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#33] opened 2018-05-10 11:28 UTC
Following recent changes to IAM permissions, the 'Delete user' button now throws an error and doesn't delete the user:

![image](https://user-images.githubusercontent.com/2608005/39867608-9521df38-544d-11e8-89ca-2fcaf520a6dc.png)

```
Internal Error
500 - {“detail”:“An error occurred (DeleteConflict) when calling the DeleteRole operation: Cannot delete entity, must delete policies first.“}
```

**Comment by xoen** [comment] 2018-05-21 10:26
I did some digging on this and I conclude it's really weird and it shouldn't happen.

I know we [detach policies before actually deleting IAM roles](https://github.com/ministryofjustice/analytics-platform-control-panel/blob/master/control_panel_api/aws.py#L96) but I had another look if there was a regression.

According to Git we [didn't change `delete_role()/_detach_role_policies()`](https://github.com/ministryofjustice/analytics-platform-control-panel/blame/master/control_panel_api/aws.py#L93) in months.

I also manually tried locally and the `_detach_role_policies()` actually detaches the policies.

Also, I didn't find this error in Sentry the CP-API, only in the CP-UI.

Does it happen all the time or only sometimes? I wonder if it's some strange race condition caused by AWS detaching those policies asynchronously.

**Comment by xoen** [comment] 2018-05-21 10:47
Right, I managed to reproduce locally. My best guess at this time is that it's complaining about the *inline* policies, mainly `s3-access` but potentially others.

**Comment by xoen** [comment] 2018-05-21 14:20
Ticket with more details, possible solution, etc...https://trello.com/c/04FsXha3/984-cant-delete-users

**Comment by andyhd** [comment] 2018-07-17 13:34
@xoen is this issue fixed?

**Comment by xoen** [comment] 2018-07-17 13:54
@andyhd I think it is. I think I was waiting for Robin to test that but I see the ticket was moved so let's close this.

**Closed by xoen** 2018-07-17 13:54 UTC
Labels: minor bug
