### ISSUE TITLE
Stuck in unidling page

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#47] opened 2018-08-28 12:14 UTC
The new hibernation page (which has rich formatting using the control panel/gov uk template) refreshes itself in an infinite loop, never taking the user to their R Studio, even when R Studio has correctly restored.

**Comment by davidread** [comment] 2018-08-28 16:30
I experienced it. I believe it's caused by the MFA challenge change. The work-around is to hit Cmd-R to refresh the browser and it properly brings up the MFA screen and lets you access R Studio.

## Reproduce
1. Make sure you're on 102PF wifi (at least not on a corporate network, so that it challenges MFA every time)
2. On alpha cpanel click "Unidle" for R Studio
3. It shows unidling screen which reloads every 5 seconds, but never takes you to R Studio.

## Analysis
The loop requests look like:
* `https://alpha-analytics-moj.eu.auth0.com/authorize?prompt=none&response_type=code&client_id=rpYFh3GxxxAvdBSS&redirect_uri=https://davidread-rstudio.tools.alpha.mojanalytics.xyz/callback&scope=openid profile`
* `https://davidread-rstudio.tools.alpha.mojanalytics.xyz/callback?error=login_required&error_description=Multifactor%20authentication%20required`
* `https://davidread-rstudio.tools.alpha.mojanalytics.xyz/login?prompt=true`
* `https://alpha-analytics-moj.eu.auth0.com/authorize?prompt=true&response_type=code&client_id=rpYFh3GxxxAvdBSS&redirect_uri=https%3A%2F%2Fdavidread-rstudio.tools.alpha.mojanalytics.xyz%2Fcallback&scope=openid%20profile`

but if I force refresh the page it takes me to:
https://alpha-analytics-moj.eu.auth0.com/mf?state=0nOxxxxxRheqdU

## Solving it
cpanel's callback needs to spot the url parameters: `?error=login_required&error_description=Multifactor%20authentication%20required` and redirect to auth0.com/MFA instead of auth0.com/authorize.

I won't look at this straight-away, as we have higher priorities.

**Comment by davidread** [comment] 2018-10-08 09:28
Workaround is to refresh the browser (Ctrl-R / cmd-R)

**Comment by xoen** [comment] 2018-10-12 12:58
We deployed a new version of the unidler so closing this as this specific issue may not happen anymore.

**Closed by xoen** 2018-10-12 12:58 UTC
